# IMPORTANT: This is a template file. 
# Replace the base64 encoded values with your actual credentials.
# Create secrets using: kubectl create secret generic switch-secrets --from-literal=ADMIN_API_KEY="your-keys"

apiVersion: v1
kind: Secret
metadata:
  name: switch-secrets
  namespace: switch
  labels:
    app.kubernetes.io/name: switch
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded credentials
  # Example: echo -n "your-api-keys" | base64
  ADMIN_API_KEY: ""  # your-admin-api-keys (comma-separated)
  OPENAI_API_KEY: ""  # sk-your-openai-api-key
  ANTHROPIC_API_KEY: ""  # sk-ant-your-anthropic-api-key
  AWS_ACCESS_KEY_ID: ""  # AKIA1234567890ABCDEF
  AWS_SECRET_ACCESS_KEY: ""  # your-aws-secret-access-key
  TOGETHER_API_KEY: ""  # your-together-api-key
  RUNPOD_API_KEY: ""  # your-runpod-api-key
  AZURE_OPENAI_API_KEY: ""  # your-azure-api-key
  GOOGLE_SERVICE_ACCOUNT_KEY: ""  # base64 encoded JSON service account key
  MODEL_DEFINITIONS: ""  # base64 encoded JSON model configuration

---
# Example secret creation commands:
# kubectl create secret generic switch-secrets \
#   --from-literal=ADMIN_API_KEY="prod-key-1,prod-key-2" \
#   --from-literal=OPENAI_API_KEY="sk-your-openai-key" \
#   --from-literal=ANTHROPIC_API_KEY="sk-ant-your-anthropic-key" \
#   --from-literal=AWS_ACCESS_KEY_ID="AKIA1234567890ABCDEF" \
#   --from-literal=AWS_SECRET_ACCESS_KEY="your-aws-secret" \
#   --from-literal=MODEL_DEFINITIONS='{"credentialStores":{},"models":{}}' \
#   --namespace=switch