apiVersion: v1
kind: Service
metadata:
  name: switch
  namespace: switch
  labels:
    app.kubernetes.io/name: switch
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: switch
    app.kubernetes.io/instance: production

---
apiVersion: v1
kind: Service
metadata:
  name: switch-headless
  namespace: switch
  labels:
    app.kubernetes.io/name: switch
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: switch
    app.kubernetes.io/instance: production